host="127.0.0.1"
port=8000
production=false
jwt-secret="testing"
flag-secret="super-secret-flag-key"
cors-url="*"
team-code-refresh-minutes=30
container-port-range-start=40000
container-port-range-end=45000
