[server]
host = "127.0.0.1"
port = 8000
production = true
cors-url = ["*"]

[server.security]
jwt-secret = "testing"
flag-secret = "super-secret-flag-key"

[docker]
socket-url = "unix:///var/run/docker.sock" 
port-range = { start = 40000, end = 45000 }
container-timeout = "0s"
pool-size = 3
clean-orphaned = true
binding-host = "0.0.0.0"
port-retry-times = 3

[database]
host = "localhost"
port = 5432
username = "your_db_user"
password = "your_db_password"
database-name = "your_database"
ssl-mode = "disable" 

[app]
email-regex = ""
token-expiry = "10m"
totp-issuer = "intraware"
team-size = 3
ban-mode = "user"
team-container-limit = 3
flag-format = "rodan"
frontend-cache-duration = "60s"

[app.leaderboard]
user = true
team = true
debounce-timer = "30s"
full-points-threshold = 3 # this much ppl will get full points
decay-sharpness = 2.25
user-blacklist = [0,1]
team-blacklist = [0,1]
